[workspace]
members = ["."]

[package]
name = "noise"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "*"

[dev-dependencies]
itertools = "*"
image = "*"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
lto = true

[profile.release-with-debug]
inherits = "release"
debug = true
