[workspace]
members = ["."]

[package]
name = "libnoise"
version = "0.1.0"
edition = "2021"

[dependencies]
core = { path = "core" }

[dev-dependencies]
criterion = "*"
plotters = "*"
itertools = "*"
num = "*"
image = "*"
opensimplex_noise_rs = "*"
opensimplex2 = "*"

[[bench]]
name = "benchmark"
harness = false

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
lto = true

[profile.release-with-debug]
inherits = "release"
debug = true
